# Online data collectionn notebook

In [ ]:
import requests
import pandas as pd
import numpy as np
from pathlib import Path
from dotenv import load_dotenv 
from tqdm import tqdm
import io
import xlrd

In [21]:
PROJECT_ROOT = Path.cwd().parent
BIRTHS_DIR = PROJECT_ROOT/"data"/"raw"/"births"
CASUALTIES_DIR = PROJECT_ROOT/"data"/"raw"/"casualties"
POPULATION_DIR = PROJECT_ROOT/"data"/"raw"/"population"
BIRTHS_DIR.mkdir(parents=True, exist_ok=True)
CASUALTIES_DIR.mkdir(parents=True, exist_ok=True)
POPULATION_DIR.mkdir(parents=True, exist_ok=True)

In [22]:
print(PROJECT_ROOT)
print(BIRTHS_DIR)
print(CASUALTIES_DIR)
print(POPULATION_DIR)

g:\Projects\returning-soldier-effect
g:\Projects\returning-soldier-effect\data\raw\births
g:\Projects\returning-soldier-effect\data\raw\casualties
g:\Projects\returning-soldier-effect\data\raw\population

## Source 1: Our World in Data — Sex Ratio at Birth

In [27]:
headers = {"User-Agent": "Mozilla/5.0"}
url = "https://ourworldindata.org/grapher/sex-ratio-at-birth.csv?v=1&csvType=full&useColumnShortNames=true"
response = requests.get(url, headers=headers)

srb_data = pd.read_csv(io.StringIO(response.text))

In [28]:
srb_data.head()

,entity,code,year,sex_ratio__sex_all__age_0__variant_estimates,owid_region
0,Afghanistan,AFG,1950,99.845600,Asia
1,Afghanistan,AFG,1951,101.636910,Asia
2,Afghanistan,AFG,1952,101.716720,Asia
3,Afghanistan,AFG,1953,101.792810,Asia
4,Afghanistan,AFG,1954,101.880745,Asia

In [34]:
srb_data["entity"].unique()

<ArrowStringArray>
[        'Afghanistan',         'Africa (UN)',             'Albania',
             'Algeria',      'American Samoa',       'Americas (UN)',
             'Andorra',              'Angola',            'Anguilla',
 'Antigua and Barbuda',
 ...
             'Vanuatu',             'Vatican',           'Venezuela',
             'Vietnam',   'Wallis and Futuna',      'Western Sahara',
               'World',               'Yemen',              'Zambia',
            'Zimbabwe']
Length: 256, dtype: str

In [35]:
srb_data.to_csv(BIRTHS_DIR/"owid_srb.csv", index=False)

In [36]:
list(BIRTHS_DIR.iterdir())

[WindowsPath('g:/Projects/returning-soldier-effect/data/raw/births/owid_srb.csv')]

## Source 2: HMD — Births by Sex

In [37]:
all_dfs = []

for file in BIRTHS_DIR.glob("*.txt"):
    df = pd.read_csv(file)
    all_dfs.append(df)

hmd_births = pd.concat(all_dfs, ignore_index=True)
print(hmd_births.shape)
hmd_births.head()

(3524, 12)

,PopName,Area,Sex,Year,YearReg,RefCode,Access,Births,NoteCode1,NoteCode2,NoteCode3,LDB
0,AUS,1,f,1860,1860,32,O,23262,10,8,.,1
1,AUS,1,m,1860,1860,32,O,24464,10,8,.,1
2,AUS,1,f,1861,1861,32,O,23806,10,8,.,1
3,AUS,1,m,1861,1861,32,O,25102,10,8,.,1
4,AUS,1,f,1862,1862,32,O,24896,10,8,.,1

## Source 3: HMD — Total Population by Sex

In [38]:
all_dfs = []

for file in POPULATION_DIR.glob("*.txt"):
    df = pd.read_csv(file)
    all_dfs.append(df)

hmd_population = pd.concat(all_dfs, ignore_index=True)
print(hmd_population.shape)
hmd_population.head()

(216613, 16)

,PopName,Area,Sex,Age,AgeInterval,Type,Day,Month,Year,RefCode,Access,Population,NoteCode1,NoteCode2,NoteCode3,LDB
0,AUS,1,f,0,1,O,30,6,1921,6,O,65000.0,.,.,.,1
1,AUS,1,f,1,1,O,30,6,1921,6,O,58800.0,.,.,.,1
2,AUS,1,f,2,1,O,30,6,1921,6,O,56200.0,.,.,.,1
3,AUS,1,f,3,1,O,30,6,1921,6,O,57400.0,.,.,.,1
4,AUS,1,f,4,1,O,30,6,1921,6,O,58900.0,.,.,.,1

## Source 4: HMD — Casualties

In [39]:
prio_deaths = pd.read_excel(CASUALTIES_DIR/"PRIO Battle Deaths Dataset 31.xls", engine="xlrd") 
print(prio_deaths.shape)
prio_deaths.head()

(1957, 32)

,id,year,bdeadlow,bdeadhig,bdeadbes,annualdata,source,bdversion,location,sidea,...,epend,ependdate,ependprec,gwnoa,gwnoa2nd,gwnob,gwnob2nd,gwnoloc,region,version
0,1,1946,1000,9999,1000,2,1,3.1,Bolivia,Bolivia,...,1,1946-07-21,-99.0,145,NaN,NaN,NaN,145,5,2009-4
1,1,1952,450,3000,-999,2,1,3.1,Bolivia,Bolivia,...,1,1952-04-12,-99.0,145,NaN,NaN,NaN,145,5,2009-4
2,1,1967,25,999,82,2,1,3.1,Bolivia,Bolivia,...,1,1967-10-16,-99.0,145,NaN,NaN,NaN,145,5,2009-4
3,2,1946,25,999,-999,0,0,3.1,Cambodia,France,...,0,NaT,NaN,220,NaN,NaN,NaN,811,3,2009-4
4,2,1947,25,999,-999,0,0,3.1,Cambodia,France,...,0,NaT,NaN,220,NaN,NaN,NaN,811,3,2009-4